#IIT Kanpur
#@ Author : Shashwat Bhattacharya 
#@ Author : Shubhadeep Sadhukhan 

#Version 1.0

#2D Structure function code
Structure: Kolmogorov41.cc
	mpic++ Kolmogorov41.cc -O3 -lh5si -lhdf5 -lyaml-cpp -fopenmp -o Kolmogorov41.out
	#CC main.cc -DBZ_DEBUG -L/home/x_sadhuks/local/lib/libblitz.a -lh5si -lhdf5 -lyaml-cpp -fopenmp -o main.out
	#CC main.cc -O2 -lh5si -lhdf5 -lyaml-cpp -fopenmp -o main.out
